id = "resonance-with-hatsune-miku"
name = "Resonance with Hatsune Miku"
version = "0.1.0"
schema_version = 1
authors = ["yuzu"]
description = "Resonance with Hatsune Miku - A custom theme for Zed inspired by Hatsune Miku's color palette."
repository = "https://github.com/yuzukq/zed-theme-Resonance-with-HatsuneMiku"
